"""users devices runs analyses

Revision ID: 0774885df36f
Revises: 761ac6b41e1e
Create Date: 2026-09-02 22:51:28.277210

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.models.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0774885df36f"
down_revision: str | Sequence[str] | None = "761ac6b41e1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("disabled_at", app.models.types.TZDateTime(timezone=True), nullable=True),
        sa.Column(
            "sessions_invalidated_at", app.models.types.TZDateTime(timezone=True), nullable=False
        ),
        sa.Column("created_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", app.models.types.TZDateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", app.models.types.TZDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_device_tokens_user_id"), "device_tokens", ["user_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("client_run_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("ended_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column("client_summary", sa.JSON(), nullable=False),
        sa.Column("gpx_blob_key", sa.String(), nullable=False),
        sa.Column("gpx_sha256", sa.String(length=64), nullable=False),
        sa.Column("gpx_bytes", sa.Integer(), nullable=False),
        sa.Column("source_platform", sa.String(length=50), nullable=False),
        sa.Column("source_app_version", sa.String(length=50), nullable=False),
        sa.Column("created_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "client_run_id", name="uq_runs_user_client_run_id"),
    )
    op.create_index("ix_runs_user_started_at", "runs", ["user_id", "started_at"], unique=False)
    op.create_table(
        "run_analyses",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "done", "failed", name="analysisstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("computed_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_analyses")
    op.drop_index("ix_runs_user_started_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_device_tokens_user_id"), table_name="device_tokens")
    op.drop_table("device_tokens")
    op.drop_table("users")
    # ### end Alembic commands ###
