"""web sessions

Revision ID: c9e96b644fd5
Revises: e685e7d581a8
Create Date: 2026-09-04 16:08:31.284762

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.models.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9e96b644fd5"
down_revision: str | Sequence[str] | None = "e685e7d581a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", app.models.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", app.models.types.TZDateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_web_sessions_user_id"), "web_sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_web_sessions_user_id"), table_name="web_sessions")
    op.drop_table("web_sessions")
    # ### end Alembic commands ###
